### ISSUE TITLE
No protocol specified

### ISSUE THREAD

**Issue by GoogleASC** [ShulkerSakura/Linux-Wine-Configuration#1]
root@Asxc:/home/asxc/wine/Linux-Wine-Configuration-master# winecfg
No protocol specified
002b:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
002b:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.

**Comment by ShulkerSakura** [comment]
I would more like to see a screenshot of your terminal error.

**Comment by GoogleASC** [comment]
Oh my God, I restarted the system and it runs successfully.
Thanks
